### ISSUE TITLE
Consider random.choice in the survey spoof script

### ISSUE THREAD

**Issue by danielbulger** [KealanAU/Python#1]
Instead of using the `randrange` function see: `rand_choice = list(choices_survey.values())[randrange(5)]`

to select a random value from the `choices_survey` dictionary consider instead using the `choice` function as described at [https://docs.python.org/3/library/random.html](url)

This has the benefit of not needing to edit the range should the dictionary be resized and would be the more 'python' way of writing this code.

**Comment by KealanAU** [comment]
Hi Daniel, 

Thanks for the pick up on how to create a more scaleable script by using the random module's choice() function. 

Please re open if this is not to your liking. 

Cheers, 

KealanAU
